-- Hospital Readmission analytics in Snowflake
-- Paste into a Snowsight worksheet after loading the READMISSIONS table,
-- or run load_and_analyze.py to load + run programmatically.

USE WAREHOUSE COMPUTE_WH;
USE DATABASE READMISSIONS_DB;
USE SCHEMA ANALYTICS;

-- 1. Readmission rate by diagnosis
SELECT PRIMARY_DIAGNOSIS,
       COUNT(*) AS PATIENTS,
       SUM(IFF(READMITTED_30_DAYS='Yes',1,0)) AS READMITTED,
       ROUND(AVG(IFF(READMITTED_30_DAYS='Yes',1,0))*100,2) AS READMIT_RATE_PCT
FROM READMISSIONS
GROUP BY PRIMARY_DIAGNOSIS
ORDER BY READMIT_RATE_PCT DESC;

-- 2. Highest-risk diagnosis (Snowflake QUALIFY + ROW_NUMBER)
SELECT * FROM (
  SELECT PRIMARY_DIAGNOSIS,
         ROUND(AVG(IFF(READMITTED_30_DAYS='Yes',1,0))*100,2) AS READMIT_RATE_PCT
  FROM READMISSIONS
  GROUP BY PRIMARY_DIAGNOSIS
)
QUALIFY ROW_NUMBER() OVER (ORDER BY READMIT_RATE_PCT DESC) = 1;

-- 3. Each insurance type's share of all readmissions (RATIO_TO_REPORT window)
SELECT INSURANCE_TYPE,
       COUNT(*) AS PATIENTS,
       SUM(IFF(READMITTED_30_DAYS='Yes',1,0)) AS READMITTED,
       ROUND(RATIO_TO_REPORT(SUM(IFF(READMITTED_30_DAYS='Yes',1,0)))
             OVER ()*100,1) AS PCT_OF_ALL_READMITS
FROM READMISSIONS
GROUP BY INSURANCE_TYPE
ORDER BY READMITTED DESC;

-- 4. Followup scheduling effect on readmission
SELECT FOLLOWUP_SCHEDULED,
       COUNT(*) AS PATIENTS,
       ROUND(AVG(IFF(READMITTED_30_DAYS='Yes',1,0))*100,2) AS READMIT_RATE_PCT
FROM READMISSIONS
GROUP BY FOLLOWUP_SCHEDULED
ORDER BY READMIT_RATE_PCT DESC;
